name: Build Packages dev

on:
  workflow_dispatch:

jobs:
  build:
    name: build ${{ matrix.arch }}-${{ matrix.branch }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        branch:
          - SNAPSHOT

    steps:
    - name: Set timezone
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        date

    - name: System info
      run: |
        lscpu | grep -E '^Architecture|^CPU\(s\):|^Model name'
        uname -sr
        lsb_release -a
        free -h

    - name: Build
      uses: apoiston/actions@dev
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

    - name: Compress
      working-directory: openwrt-sdk
      run: |
        tar -c -z -f nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz -C bin/packages/${{ matrix.arch }}/nikki . 
        mkdir -p public/${{ matrix.branch }}/${{ matrix.arch }}
        mv bin/packages/${{ matrix.arch }}/nikki public/${{ matrix.branch }}/${{ matrix.arch }}
        tar -c -z -f nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz public/${{ matrix.branch }}/${{ matrix.arch }}

    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: nikki_${{ matrix.arch }}-${{ matrix.branch }}
        path: openwrt-sdk/nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz

feed:
  needs: build
  name: feed
  runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download
      uses: actions/download-artifact@main
      with:
        pattern: nikki_*
        merge-multiple: true

    - name: Uncompress
      run: |
        for file in nikki_*.tar.gz; do tar -x -z -f "$file"; done

    - name: Commit SNAPSHOT
      working-directory: public
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add SNAPSHOT
        git commit -m "Update Feed"
        git push origin HEAD:${{ github.ref }}

  clean:
    needs: feed
    name: clean
    runs-on: ubuntu-latest

    steps:
      - name: Clean pages
        uses: apoiston/actions@clean
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
