name: build

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  get_latest_info:
    runs-on: ubuntu-latest
    outputs:
      latest_pkg_version: ${{ steps.get_latest_info.outputs.latest_pkg_version }}
      latest_pkg_source_version: ${{ steps.get_latest_info.outputs.latest_pkg_source_version }}
      latest_pkg_mirror_hash: ${{ steps.get_latest_info.outputs.latest_pkg_mirror_hash }}
      commit_sha_short: ${{ steps.get_latest_info.outputs.commit_sha_short }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: 'MetaCubeX/mihomo'
          ref: 'Alpha'
          path: 'mihomo'

      - name: get latest info
        id: get_latest_info
        run: |
          commit_date=$(git -C mihomo log -n 1 --format="%cd" --date=format:"%Y.%m.%d")
          commit_sha=$(git -C mihomo rev-parse HEAD)
          commit_sha_short=$(git -C mihomo rev-parse --short HEAD)
          git -C mihomo config tar.xz.command "xz -c"
          git -C mihomo archive --output=$PWD/mihomo.tar.xz HEAD
          echo "commit_sha_short=$commit_sha_short" >> $GITHUB_OUTPUT          
          echo "latest_pkg_version=${commit_date}~${commit_sha_short}" >> $GITHUB_OUTPUT
          echo "latest_pkg_source_version=Alpha" >> $GITHUB_OUTPUT
          echo "latest_pkg_mirror_hash=$(sha256sum mihomo.tar.xz | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

  build:
    needs: get_latest_info
    name: build ${{ matrix.arch }}-${{ matrix.branch }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        branch:
          - SNAPSHOT
          - openwrt-24.10

    steps:
      - name: set timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date +"%Y-%m-%d %H:%M:%S"
          
      - name: system info
        run: |
          date +"%Y-%m-%d %H:%M:%S"
          lscpu | grep -E '^Architecture|^CPU\(s\):|^Model name'
          uname -sr
          lsb_release -a
          free -h
          
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: apoiston/openwrt-nikki
          ref: main
          path: openwrt-nikki

      - name: update
        run: |
          sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${{ needs.get_latest_info.outputs.latest_pkg_version }}/" openwrt-nikki/nikki/Makefile
          sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=1/" openwrt-nikki/nikki/Makefile
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=${{ needs.get_latest_info.outputs.latest_pkg_source_version }}/" openwrt-nikki/nikki/Makefile
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=${{ needs.get_latest_info.outputs.latest_pkg_mirror_hash }}/" openwrt-nikki/nikki/Makefile
          if ! grep -q "PKG_BUILD_VERSION:=" openwrt-nikki/nikki/Makefile; then
              sed -i '/PKG_BUILD_TIME:=/i PKG_BUILD_VERSION:=' openwrt-nikki/nikki/Makefile
          fi
          sed -i "s/PKG_BUILD_VERSION:=.*/PKG_BUILD_VERSION:=alpha-${{ needs.get_latest_info.outputs.commit_sha_short }}/" openwrt-nikki/nikki/Makefile
          sed -i '/GO_PKG_LDFLAGS_X:=/ s/PKG_SOURCE_VERSION/PKG_BUILD_VERSION/' openwrt-nikki/nikki/Makefile
          
      - name: show info
        run: |
          ls -l $GITHUB_WORKSPACE
          grep -o 'PKG_VERSION:.*' openwrt-nikki/nikki/Makefile | cut -d '=' -f 2
          grep -o 'PKG_BUILD_VERSION:.*' openwrt-nikki/nikki/Makefile | cut -d '=' -f 2

      - name: build
        uses: apoiston/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: apps
          PACKAGES: luci-app-nikki
          INDEX: 1
          NO_REFRESH_CHECK: true
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          
      - name: compress
        run: |
          tar -c -z -f apps_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz -C bin/packages/${{ matrix.arch }}/apps .
          mkdir -p public/${{ matrix.branch }}/${{ matrix.arch }}
          mv bin/packages/${{ matrix.arch }}/apps public/${{ matrix.branch }}/${{ matrix.arch }}
          tar -c -z -f apps_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz public/${{ matrix.branch }}/${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: apps_${{ matrix.arch }}-${{ matrix.branch }}
          path: apps_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz
          
  clean:
    name: clean
    runs-on: ubuntu-latest

    steps:
      - name: clean
        uses: apoiston/actions@clean
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          project_name: "infinityapps"
          days_old: "7"