
name: Build snapshot

on:
  workflow_dispatch:

jobs:
  build:
    name: build snapshot
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false

    steps:
    - name: Set timezone
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        date

    - name: System info
      run: |
        lscpu | grep -E '^Architecture|^CPU\(s\):|^Model name'
        uname -sr
        lsb_release -a
        free -h

    - name: Build
      uses: apoiston/action@sdk

    - name: Compress
      working-directory: ./openwrt-sdk
      run: |
        tar -c -z -f nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz -C bin/packages/${{ matrix.arch }}/nikki .
        mkdir -p public/${{ matrix.branch }}/${{ matrix.arch }}
        mv bin/packages/${{ matrix.arch }}/nikki public/${{ matrix.branch }}/${{ matrix.arch }}
        tar -c -z -f nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz public/${{ matrix.branch }}/${{ matrix.arch }}

    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: nikki_${{ matrix.arch }}-${{ matrix.branch }}
        path: nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz

  feed:
    needs: build
    name: feed
    runs-on: ubuntu-latest

    steps:
      - name: Download
        uses: actions/download-artifact@main
        with:
          pattern: nikki_*
          merge-multiple: true
      
      - name: Uncompress
        run: |
          for file in nikki_*.tar.gz; do tar -x -z -f "$file"; done

      - name: Feed
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Update Feed
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com

  clean:
    needs: feed
    name: clean
    runs-on: ubuntu-latest

    steps:
      - name: Clean pages
        uses: apoiston/actions@clean
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
